version: '2'
services:
    employee:
        build: .
        container_name: "employee"
        image: employee
        ports:
            - 8890:8890
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null 
