---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    serviceType: message-broker
  ports:
    - port: 5672
      name: broker
      targetPort: 5672
    - port: 15672
      name: admin
      targetPort: 15672
  type: NodePort
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: infrastructure
        serviceType: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
          - containerPort: 5672
          - containerPort: 15672
---

apiVersion: v1
kind: Service
metadata:
  name: spring-app
  labels:
    run: spring-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    run: spring-app
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: spring-app
    spec:
      containers:
      - name: spring-app
        image:  nameduttu/spring1:new
        ports:
        - containerPort: 8080 
