apiVersion: v1

kind: Service

metadata:

  name: my-emp

  labels:

    run: my-emp

spec:

  ports:

  - port: {{ .Values.service.port }}

    targetPort: {{ .Values.frontendport}}

    protocol: TCP

  type: {{ .Values.global.type }}

  selector:

    run: my-emp


