---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    serviceType: message-broker
  ports:
    - port: 5672
      name: broker
      targetPort: 5672
    - port: 15672
      name: admin
      targetPort: 15672
  type: NodePort
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: infrastructure
        serviceType: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
          - containerPort: 5672
          - containerPort: 15672
---

apiVersion: v1
kind: Service
metadata:
  name: spring-sender
  labels:
    run: spring-sender
spec:
  ports:
  - port: 9095
    targetPort: 9095
    protocol: TCP
  type: NodePort
  selector:
    run: spring-sender
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-sender
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: spring-sender
    spec:
      containers:
      - name: spring-sender
        image:  nameduttu/springsender:1
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: spring-listener
  labels:
    run: spring-listener
spec:
  ports:
  - port: 9096
    targetPort: 9096
    protocol: TCP
  type: NodePort
  selector:
    run: spring-listener
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-listener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: spring-listener
    spec:
      containers:
      - name: spring-listener
        image:  nameduttu/springlistener:1
        ports:
        - containerPort: 9096

